# Generated by Django 4.1.7 on 2023-03-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='detail',
            new_name='details',
        ),
    ]
